### PR TITLE
Modified docs for sphinx, removed html generation errors for sphinx, …

### PR DESCRIPTION
**Pull request by ajshastri**
1. Fixed errors during `make html`
2. fixed the rest of the documentation
3. Removed the `pyetrade.\exception_module` for now from the pyetrade.rst to resolve errors related to module absence.
4. Created an examples page in documentation for beginners to easily follow (orders examples pending)
5. imported alerts to __init__.py to standardize `import pyetrade`
6. Bumping version to 1.2.1 because of the change to __init__.py

@jessecooper  Please let me know if you want me to change any of the above.

### CODE REVIEW

**Comment by ajshastri** [comment]
@jessecooper 

The new docs should look like this

https://docsfixpyetrade.readthedocs.io/en/docs-fix/pyetrade.html#module-pyetrade.order

**Comment by jessecooper** [comment]
@ajshastri Thank you for the PR

**Comment by jessecooper** [comment]
The docs have never looks so good. Awesome job!

**Comment by ajshastri** [comment]
My pleasure. Nothing like learning a new library like jumping into the deep end. :D

**Pull request merged**
