### PR TITLE
Changes to docs and version

### PR DESCRIPTION
**Pull request by ajshastri**
Hi,
I've made the following changes:
1. Changed setup.py and docs/conf.py to use `__version__` from pyetrade/init.py (one place for them all)
2. Changed docs/conf.py html_theme_options to allow full page utilization (using various :param: caused indents triggering too many word wraps)
3. Added `:param:`, `:description:`, `:returns:`, `:rtype:` and `:etradeRef:` to help doc look better and `:class:` for where to retrieve some of the parameters like `account_id_key`. 
4. Rectified the warning during `make html` builds for the `accounts.py`

Docs can be viewed here https://pyetradedocstest.readthedocs.io/en/accounts-docs-fix/pyetrade.html#module-pyetrade.accounts

### CODE REVIEW

**Comment by ajshastri** [comment]
@jessecooper I wasn't sure if this was the way to make changes. Please review.

**Comment by jessecooper** [comment]
LGTM, only additional thing that would need to change is the removal of https://github.com/jessecooper/pyetrade/blob/master/.bumpversion.cfg#L6 in the bumpversion configuration. Do you mind adding that to this PR?

**Comment by ajshastri** [comment]
@jessecooper I'll work on modifying the remaining classes for the docs in another branch. Will try to complete it by end of the next week.

**Comment by jessecooper** [comment]
@ajshastri Thanks for the PR look forward to seeing the other one.

**Pull request merged**
